/* ------------------------------------------------------------------
   LEBIVEST — catalogue
   Static product data referencing /images. Rendered client-side.
   The signature of the house: Anatolian kilim motifs rendered in
   gold thread on quiet-luxury tailoring.
------------------------------------------------------------------ */

export const CURRENCY = "$";

export const products = [
  /* ---------------- MEN · Trousers (the kilim line) ---------------- */
  {
    id: "lacivert-keten-pantolon",
    name: "Navy Linen Trousers",
    nameTr: "Lacivert Keten Pantolon",
    category: "men",
    line: "Trousers",
    price: 380,
    color: "Navy",
    fabric: "Pure linen, gold kilim side-stripe",
    tagline: "Heritage thread, modern line",
    image: "/images/designs/3.png",
    description:
      "Wide, fluid linen trousers traced with a hand-guided Kurdish kilim motif in gold thread down the side seam. Quiet by day, ceremonial by candlelight.",
    details: ["Relaxed straight leg", "Natural linen, breathable hand", "Gold kilim side detail", "Hidden hook & zip"],
    sizes: ["30", "32", "34", "36", "38"],
    badge: "Signature",
  },
  {
    id: "antrasit-keten",
    name: "Anthracite Herringbone Trousers",
    nameTr: "Antrasit Keten",
    category: "men",
    line: "Trousers",
    price: 410,
    color: "Anthracite",
    fabric: "Wool-linen herringbone",
    tagline: "Strong stance, quiet luxury",
    image: "/images/designs/4.png",
    description:
      "Tailored herringbone trousers in deep anthracite — restraint cut close to the body. A wardrobe spine for the considered man.",
    details: ["Tailored slim fit", "Wool-linen herringbone", "Subtle tonal side trace", "Season 2026"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "koyu-vizon-keten",
    name: "Dark Mink Linen Trousers",
    nameTr: "Koyu Vizon Keten",
    category: "men",
    line: "Trousers",
    price: 390,
    color: "Dark Mink",
    fabric: "Pure linen, gold kilim side-stripe",
    tagline: "Cultural root, modern line",
    image: "/images/designs/5.png",
    description:
      "A warm mink-brown linen with a golden kilim ribbon running the length of the leg — the house signature in its most wearable tone.",
    details: ["Relaxed straight leg", "Gold-tone kilim side-stripe", "Natural linen", "Unlined, lightweight"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "kum-beji-keten",
    name: "Sand Beige Linen Trousers",
    nameTr: "Kum Beji Keten",
    category: "men",
    line: "Trousers",
    price: 360,
    color: "Sand Beige",
    fabric: "Pure linen, navy kilim side-stripe",
    tagline: "Natural flow, elegant detail",
    image: "/images/designs/6.png",
    description:
      "Soft sand linen with a navy kilim motif at the seam. Generous through the leg, made to move with the desert light.",
    details: ["Relaxed wide fit", "Navy kilim side detail", "Natural linen", "Pleated front"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "gece-mavisi",
    name: "Midnight Blue Trousers",
    nameTr: "Gece Mavisi",
    category: "men",
    line: "Trousers",
    price: 420,
    color: "Midnight Blue",
    fabric: "Wool-silk blend, metallic kilim",
    tagline: "Cinematic elegance, a golden trace",
    image: "/images/designs/7.png",
    description:
      "Midnight wool-silk with a fine metallic gold kilim motif — drape and fall engineered for evening. The trouser that holds a room.",
    details: ["Fluid evening drape", "Wool-silk blend", "Metallic gold kilim", "Tailored mid-rise"],
    sizes: ["30", "32", "34", "36", "38"],
    badge: "Evening",
  },
  {
    id: "zeytin-yesili-keten",
    name: "Olive Linen Co-ord",
    nameTr: "Zeytin Yeşili Keten",
    category: "men",
    line: "Sets",
    price: 640,
    color: "Olive Green",
    fabric: "Pure linen, terracotta kilim",
    tagline: "City spirit, cultural texture",
    image: "/images/designs/8.png",
    description:
      "An olive linen overshirt and trouser, joined by a terracotta-cream kilim ribbon. Slim, urban, rooted. Sold as a co-ord.",
    details: ["Overshirt + trouser set", "Terracotta kilim side-stripe", "Slim urban silhouette", "Pure linen"],
    sizes: ["S", "M", "L", "XL"],
    badge: "Co-ord",
  },
  {
    id: "tas-grisi-keten",
    name: "Stone Grey Linen Trousers",
    nameTr: "Taş Grisi Keten",
    category: "men",
    line: "Trousers",
    price: 360,
    color: "Stone Grey",
    fabric: "Pure linen, bordeaux-gold kilim",
    tagline: "Easy stance, deep roots",
    image: "/images/designs/9.png",
    description:
      "Stone-grey linen with a bordeaux-and-gold kilim trace. Relaxed through an open hem — the everyday trouser of the house.",
    details: ["Relaxed fit, open hem", "Bordeaux-gold kilim detail", "Natural linen", "Everyday weight"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "bej-cizgili-keten",
    name: "Beige Pinstripe Trousers",
    nameTr: "Bej Çizgili Keten",
    category: "men",
    line: "Trousers",
    price: 370,
    color: "Beige Stripe",
    fabric: "Striped linen, gold motif column",
    tagline: "Relaxed cut, natural line",
    image: "/images/designs/14.png",
    description:
      "Fine-striped beige linen carrying a column of stacked kilim diamonds in gold and amber. A relaxed, considered trouser.",
    details: ["Relaxed fit", "Stacked kilim motif column", "Striped linen", "Season 2026"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "mavi-gri-cizgili",
    name: "Blue-Grey Pinstripe Trousers",
    nameTr: "Mavi-Gri Çizgili",
    category: "men",
    line: "Trousers",
    price: 390,
    color: "Blue Grey",
    fabric: "Pinstripe linen, gold kilim",
    tagline: "Slim fit, a fine line",
    image: "/images/designs/15.png",
    description:
      "A crisp blue-grey pinstripe with the gold kilim motif tracing the outseam. Slim, sharp, quietly decorated.",
    details: ["Slim fit", "Gold kilim outseam", "Pinstripe linen", "Tailored rise"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "antrasit-cizgili",
    name: "Anthracite Pinstripe Trousers",
    nameTr: "Antrasit Çizgili",
    category: "men",
    line: "Trousers",
    price: 400,
    color: "Anthracite Stripe",
    fabric: "Wool-blend pinstripe, gold kilim",
    tagline: "Modern cut, deep texture",
    image: "/images/designs/16.png",
    description:
      "Modern anthracite pinstripe in a wool blend, finished with a slim gold kilim trace. Built for the city, rooted in the loom.",
    details: ["Modern slim fit", "Slim gold kilim trace", "Wool-blend pinstripe", "All-day structure"],
    sizes: ["30", "32", "34", "36", "38"],
  },

  /* ---------------- MEN · Outerwear ---------------- */
  {
    id: "sehir-paltosu",
    name: "Double-Breasted Wool Overcoat",
    nameTr: "Şehir Paltosu",
    category: "men",
    line: "Outerwear",
    price: 1450,
    color: "Charcoal",
    fabric: "Pressed virgin wool",
    tagline: "The architecture of winter",
    image: "/images/models/7.png",
    description:
      "A double-breasted overcoat in pressed virgin wool, cut just below the knee. Structured shoulder, fluid skirt — the long line of the house.",
    details: ["Double-breasted", "Pressed virgin wool", "Below-knee length", "Horn buttons"],
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "hafif-blazer",
    name: "Soft-Tailored Blazer",
    nameTr: "Hafif Blazer",
    category: "men",
    line: "Outerwear",
    price: 890,
    color: "Navy",
    fabric: "Wool-linen, unstructured",
    tagline: "Ease, tailored",
    image: "/images/models/6.png",
    description:
      "An unstructured navy blazer in wool-linen — no lining, no rigidity. Worn over a tee with chinos, it carries the whole day.",
    details: ["Unstructured, unlined", "Wool-linen blend", "Patch pockets", "Natural shoulder"],
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "keten-gomlek-ceket",
    name: "Linen Overshirt",
    nameTr: "Keten Gömlek Ceket",
    category: "men",
    line: "Outerwear",
    price: 440,
    color: "Stone",
    fabric: "Heavy washed linen",
    tagline: "Between shirt and coat",
    image: "/images/models/8.png",
    description:
      "A heavy washed-linen overshirt that lives between a shirt and a jacket. Throw it over a grey tee and pleated trousers.",
    details: ["Shirt-jacket cut", "Heavy washed linen", "Chest & side pockets", "Mother-of-pearl buttons"],
    sizes: ["S", "M", "L", "XL"],
  },

  /* ---------------- WOMEN · Dresses & Outerwear ---------------- */
  {
    id: "genis-paca-tulum",
    name: "Wide-Leg Jumpsuit",
    nameTr: "Geniş Paça Tulum",
    category: "women",
    line: "Dresses",
    price: 720,
    color: "Chocolate",
    fabric: "Fluid crepe",
    tagline: "One line, head to floor",
    image: "/images/models/1.png",
    description:
      "A wrap-front jumpsuit in fluid chocolate crepe, falling to a sweeping wide leg. A single, uninterrupted gesture of a garment.",
    details: ["Wrap front, self-tie", "Fluid crepe", "Sweeping wide leg", "Concealed zip"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Signature",
  },
  {
    id: "tek-omuz-abiye",
    name: "One-Shoulder Gown",
    nameTr: "Tek Omuz Abiye",
    category: "women",
    line: "Dresses",
    price: 980,
    color: "Midnight Navy",
    fabric: "Draped jersey-silk",
    tagline: "Asymmetry, perfected",
    image: "/images/models/4.png",
    description:
      "A midnight one-shoulder gown, gathered at the waist and falling clean to the floor. Draped jersey-silk that moves like water.",
    details: ["One-shoulder neckline", "Gathered waist", "Draped jersey-silk", "Floor length"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Evening",
  },
  {
    id: "yun-pelerin-palto",
    name: "Wool Cape Coat",
    nameTr: "Yün Pelerin Palto",
    category: "women",
    line: "Outerwear",
    price: 1650,
    color: "Camel",
    fabric: "Brushed wool-cashmere",
    tagline: "Wrapped in warm light",
    image: "/images/models/5.png",
    description:
      "A floor-grazing cape coat in brushed wool-cashmere, camel as the late sun. It falls from the shoulder and trails behind you.",
    details: ["Full cape silhouette", "Brushed wool-cashmere", "Floor-grazing length", "Tonal hook closure"],
    sizes: ["XS/S", "M/L"],
    badge: "Atelier",
  },
  {
    id: "oversize-keten-palto",
    name: "Oversized Linen Coat",
    nameTr: "Oversize Keten Palto",
    category: "women",
    line: "Outerwear",
    price: 1250,
    color: "Oatmeal",
    fabric: "Textured pure linen",
    tagline: "Borrowed lines, perfected",
    image: "/images/models/2.png",
    description:
      "An oversized double-breasted coat in textured oatmeal linen — masculine cut, feminine fall. The summer outer layer of the house.",
    details: ["Oversized double-breasted", "Textured pure linen", "Drop shoulder", "Self belt"],
    sizes: ["XS/S", "M/L"],
  },
  {
    id: "drapeli-pelerin-takim",
    name: "Draped Cape Set",
    nameTr: "Drapeli Pelerin Takım",
    category: "women",
    line: "Sets",
    price: 890,
    color: "Charcoal",
    fabric: "Soft suede-touch jersey",
    tagline: "Movement, draped",
    image: "/images/models/3.png",
    description:
      "A cowl-draped cape top with matching wide trousers in suede-touch jersey. Charcoal, fluid, and built to move through narrow streets.",
    details: ["Cowl cape top + trousers", "Suede-touch jersey", "Wide fluid leg", "Sold as a set"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Co-ord",
  },
  {
    id: "derin-lacivert-abaya",
    name: "Gold-Embroidered Abaya",
    nameTr: "Derin Lacivert",
    category: "women",
    line: "Abaya",
    price: 840,
    color: "Deep Navy",
    fabric: "Crepe, gold-silver kilim embroidery",
    tagline: "A golden trace",
    image: "/images/models/12.png",
    description:
      "An oversized deep-navy abaya embroidered with gold-and-silver Kurdish kilim motifs across the body and cuffs. The house signature, for her.",
    details: ["Oversized abaya cut", "Gold-silver kilim embroidery", "Crepe drape", "Matching scarf"],
    sizes: ["36", "38", "40", "42", "44"],
    badge: "Signature",
  },
  {
    id: "pudra-pembe-keten-abaya",
    name: "Powder Pink Abaya",
    nameTr: "Pudra Pembe Keten",
    category: "women",
    line: "Abaya",
    price: 760,
    color: "Powder Pink",
    fabric: "Pure linen, gold kilim embroidery",
    tagline: "An elegant motif",
    image: "/images/models/13.png",
    description:
      "A powder-pink linen abaya with a rose-gold kilim motif running its length. Oversized, soft, luminous against the light.",
    details: ["Oversized abaya cut", "Rose-gold kilim embroidery", "Pure linen", "Matching scarf"],
    sizes: ["36", "38", "40", "42", "44"],
  },
  {
    id: "antrasit-abaya",
    name: "Charcoal Everyday Abaya",
    nameTr: "Antrasit Abaya",
    category: "women",
    line: "Abaya",
    price: 620,
    color: "Charcoal",
    fabric: "Matte crepe",
    tagline: "Quiet, every day",
    image: "/images/models/10.png",
    description:
      "A clean charcoal abaya in matte crepe with a slim gold pendant detail at the neck and discreet side slits. The understated daily piece.",
    details: ["Minimal A-line abaya", "Matte crepe", "Gold neck detail", "Side slits"],
    sizes: ["36", "38", "40", "42", "44"],
  },
  {
    id: "kum-beji-abaya-takim",
    name: "Open Abaya & Slip Set",
    nameTr: "Kum Beji Abaya Takım",
    category: "women",
    line: "Sets",
    price: 880,
    color: "Camel & Cream",
    fabric: "Chiffon over linen slip",
    tagline: "Layers of warm sand",
    image: "/images/models/11.png",
    description:
      "A flowing camel chiffon open-abaya layered over a cream embroidered linen slip dress. Two pieces, one warm, sand-toned silhouette.",
    details: ["Open-abaya + slip dress", "Chiffon over linen", "Tonal embroidery", "Sold as a set"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Co-ord",
  },
  {
    id: "krem-palto-takim",
    name: "Belted Coat & Trouser Set",
    nameTr: "Krem Palto Takım",
    category: "women",
    line: "Outerwear",
    price: 1100,
    color: "Cream & Camel",
    fabric: "Wool-blend coat, linen trouser",
    tagline: "Tonal, head to toe",
    image: "/images/models/9.png",
    description:
      "A long cream belted coat with embroidered cuffs over camel wide-leg trousers and a matching scarf. A complete tonal look from the atelier.",
    details: ["Belted long coat", "Embroidered cuffs", "Camel wide-leg trouser", "Matching scarf"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Atelier",
  },
];

/* ------------------------------ helpers ------------------------------ */
export const formatPrice = (value) => `${CURRENCY}${value.toLocaleString("en-US")}`;

export const getProductById = (id) => products.find((p) => p.id === id);

export const getByCategory = (category) =>
  category && category !== "all" ? products.filter((p) => p.category === category) : products.slice();

export const getRelated = (product, count = 3) =>
  products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, count);

export const featured = () => [
  getProductById("derin-lacivert-abaya"),
  getProductById("gece-mavisi"),
  getProductById("yun-pelerin-palto"),
  getProductById("lacivert-keten-pantolon"),
].filter(Boolean);
